#! /bin/bash
CTRL_DIR=$(cd $(dirname ${BASH_SOURCE[0]}); pwd)
source ${CTRL_DIR}/config/sys.env
# rebar release的运行管理脚本
SHELL_SCRIPT=${CTRL_DIR}/bin/mid_web

start() {
  $SHELL_SCRIPT console -detached "$@"
}

live() {
  $SHELL_SCRIPT console "$@"
}

stop() {
  $SHELL_SCRIPT stop "$@"
}

game_cmd() {
  $SHELL_SCRIPT eval wlib_ctrl:command\(\""$@"\"\).
}

debug() {
  $SHELL_SCRIPT remote_console
}

eval() {
  $SHELL_SCRIPT eval "$@"
}

l() {
  # 链接节点需要自己是一个有名字的节点，不能是nonode@nohost
  RANDOM_STR=$(gen_random_str)
  IP=$(get_ip)
  ERL_FLAGS=" -name load_module_${RANDOM_STR}@${IP} -setcookie load_module_${RANDOM_STR} " $ESCRIPT ${CTRL_DIR}/script/load_module.es "$@"
}

gen_random_str() {
  cat /dev/urandom | head -n 10 | md5sum | head -c 10
}

get_ip() {
    IP=($(ifconfig -a|grep inet|grep -v 127.0.0.1|grep -v inet6|awk '{print $2}'|tr -d \"addr:\"))
    echo $IP[0]
}

case "$1" in
  "start")
    start "$@"
    ;;
  "live")
    live "$@"
    ;;
  "stop")
    stop "$@"
    ;;
  "restart")
    stop "$@"
    start "$@"
    ;;
  "debug")
    debug "$@"
    ;;
  "game_cmd")
    shift
    game_cmd "$@"
    ;;
  "eval")
    shift
    eval "$@"
    ;;
  "c")
    shift 
    $ESCRIPT ${CTRL_DIR}/script/compile_file.es "$@"
    ;; 
  "ct")
    shift 
    $ESCRIPT ${CTRL_DIR}/script/compile_file.es \$compile_file_to_dir "$@"
    ;; 
  "l")
    shift
    l "$@"
    ;;
  "cl")
    shift
    $ESCRIPT ${CTRL_DIR}/script/compile_file.es "$@" && l "$@"
    ;;
  "deploy")
    shift
    sh ${CTRL_DIR}/script/deploy.sh $PROJECT_NAME
    ;;
  *)
    echo "    start 启动节点"
	echo "    live 交互式启动"
    echo "    stop 停止服务"
    echo "    game_cmd 执行wlib_ctrl:command(CMD)"
    echo "    c 编译文件到_build/default/rel/lib: c mod1 mod2..."
    echo "    ct 编译文件到指定目录 ct dir mod1 mod2..."
    echo "    l 加载模块：l mod1 mod2..."
    echo "    debug 连接到运行中的节点"
    echo "    deploy 打包发布 PROJCECT_NAME为sys.env配置值"
    ;;
esac

